name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    # strategy:
    #   matrix:
    #     node-version: [v20.10.0]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    #env:
    #MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      # - uses: actions/checkout@v4
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: "npm"

      - name: Move to Project Directory
        run: cd /home/shishir/traveldeeploy1

      - name: Pull latest code
        run: |
          git pull origin main

      - name: Install Dependencies
        run: npm install

      - name: Build Applications
        run: npm run build

      - name: Restart PM2 Process
        run: pm2 restart 0
    # - run: npm ci
    # - run: npm run build --if-present
    # - name: Change Directory
    #   run: cd /home/shishir/actions-runner/_work/traveldeeploy1/traveldeeploy1
    # - name: Restart PM2
    #   run: pm2 restart 0
