name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [v20.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    # env:
    #   MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Restore Cached Dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-${{ matrix.node-version }}-

      - name: Restore Next.js Cache
        id: cache-next
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: nextjs-build-${{ github.sha }}
          restore-keys: |
            nextjs-build-

      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit

      - name: Build Next.js App
        run: npm run build --if-present

      - name: Save Next.js Cache
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: nextjs-build-${{ github.sha }}

      # - name: Change Directory
      #   run: cd /home/shishir/actions-runner/_work/traveldeeploy1/traveldeeploy1
      - name: Restart PM2
        run: pm2 restart 0
