name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [v20.10.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    # env:
    #   MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Restore Next.js Pre-Built Cache
        run: |
          if [ -f /home/shishir/next-cache.tar.gz ]; then
            tar -xzf /home/shishir/next-cache.tar.gz -C .
            echo "Next.js cache restored."
          else
            echo "No Next.js cache found. Running fresh build."
          fi

      - name: Restore Node Modules Cache
        run: |
          if [ -f /home/shishir/node_modules_cache.tar.gz ]; then
            tar -xzf /home/shishir/node_modules_cache.tar.gz -C .
            echo "Node modules cache restored."
          else
            echo "No cache found, installing dependencies."
          fi

      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline --no-audit

      - name: Save Node Modules Cache
        run: tar -czf /home/shishir/node_modules_cache.tar.gz node_modules

      - name: Copy Configurations
        run: cp /home/shishir/.env /home/shishir/actions-runner/_work/traveldeeploy1/traveldeeploy1/.env

      - name: Preserve Uploads Directory
        run: |
          ln -s /home/shishir/actions-runner/uploads /home/shishir/actions-runner/_work/traveldeeploy1/traveldeeploy1/uploads

      - name: Build Next.js App
        run: npm run build --if-present

      - name: Save Next.js Cache
        run: tar -czf /home/shishir/next-cache.tar.gz .next/cache

      # - name: Change Directory
      #   run: cd /home/shishir/actions-runner/_work/traveldeeploy1/traveldeeploy1
      - name: Restart PM2
        run: pm2 restart 0
